/****************************************/
/* Cool Herders                         */
/* http://harmlesslion.com              */
/* Copyright 2009 HarmlessLion LLC      */
/* levels.c                             */
/****************************************/

#include <stdio.h>

#include "kosemulation.h"

#include "sprite.h"
#include "levels.h"
#include "collide.h"
#include "cool.h"
#include "rand.h"
#include "control.h"
#include "sound.h"
#include "menu.h"		// for globals
#include "storymode.h"
#include "font.h"
#include "mapscr_manager.h"
#include "menuscr_manager.h"
#include "vmu_logo.h"
#include "special.h"
#include "sheep.h"

// Externs from cool.c, needed for DrawLevel()
extern int	nBgAnimA, nBgAnimB, nBgAnimC;
extern int	nBgSpeedA, nBgSpeedB, nBgSpeedC;
extern int	nBgCountA, nBgCountB, nBgCountC;
extern fx16	sFx;
extern int  nTimeLeft;
extern int	nFrames;
extern int	fPaused;
extern int	nGameCountdown;
extern int  gHumanPlayer;
extern int	isMultiplayer;
extern int	nTotalSheep;
extern int 	g_DestructiblesLeft;

extern unsigned int nGameFrames;
extern int gStageSpecialEffect;
extern int level;

extern pvr_ptr_t txr_sprites;
extern pvr_ptr_t txr_level;
extern pvr_ptr_t txr_sheep;
extern pvr_ptr_t txr_herder[6];
extern pvr_ptr_t pal_sprites, pal_sheep, pal_level, pal_herder[6];

extern TXRMAP txrmap_sheep[];
extern TXRMAP txrmap_sprites[];

extern int nOffsetX, nOffsetY;

TXRMAP LevelMap[300];

// Screens are 21x16, generated by the map editor
// 3 chars per tile.
// First is the page, 1-3. 3 is always destructible impassible, 1-2 are freeform
// Second is the type: .=flat, passable; -=flat, unpassable; /=3D, unpassable (page 1 and 2 only)
// for tile page 3, the second is the tile that this object sits on based on page 1 if uppercase or 2 if lowercase
// Third is the tile number, A-Y (goes across)

char Level[NUMLEVELS][LEVELBYTES] =
// NOTE!! One string each - so comma goes only at the end of a level! :)
{
	// ******* Level 0 - New Zealand ********/
	// NZ STAGE 1
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O"
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O"
	"2-O2-Q2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-P2-O"
	"2-O2-M1.J1.J3JA3JA3JA3JA1.J1.J1.K1.J1.J3JA3JA3JA3JA1.J1.J2-L2-O"
	"2-O2-M1.J2/G2/A2/A3AA2/A1.A2/A1.A2/A2/A2/A3AA2/A2/A2/F1.K2-L2-O"
	"2-O2-M3JA2/C1.E1.E1.E2/E1.E1.E1.E1.E1.E2/E1.E1.E1.E2/B3JA2-L2-O"
	"2-O2-M3JA2/C1.E2/E2/E2/E1.E2/E2/E2/E1.E2/E1.E2/E1.E2/B3JA2-L2-O"
	"2-O2-M3JA3CA1.E1.E1.E1.E1.E2/E1.E1.E1.E1.E1.E2/E1.E3BA3JA2-L2-O"
	"2-O2-M2/J2/C1.E2/E2/E2/E1.E2/E1.E2/E1.E2/E2/E2/E1.E2/B2/J2-L2-O"
	"2-O2-M3JA3CA1.E2/E1.E1.E1.E1.E1.E2/E1.E1.E1.E1.E1.E3BA3JA2-L2-O"
	"2-O2-M3JA2/C1.E2/E1.E2/E1.E2/E2/E2/E1.E2/E2/E2/E1.E2/B3JA2-L2-O"
	"2-O2-M3JA2/C1.E1.E1.E2/E1.E1.E1.E1.E1.E2/E1.E1.E1.E2/B3JA2-L2-O"
	"2-O2-M1.J2/I2/D2/D3DA2/D2/D2/D1.D2/D1.D2/D3DA2/D2/D2/H1.J2-L2-O"
	"2-O2-M1.K1.J3JA3JA3JA3JA1.J1.J1.J1.J1.J3JA3JA3JA3JA1.J1.J2-L2-O"
	"2-O2-S2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-R2-O"
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O",

	// NZ STAGE 2
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O"
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O"
	"2-O2-Q2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-P2-O"
	"2-O2-M1.J1.J3JA2/J3JA3JA3JA2/J2/J2/J3JA3JA3JA2/J3JA1.J1.J2-L2-O"
	"2-O2-M1.J2/G3AA3AA1.A2/A1.A1.A1.A1.A1.A2/A1.A3AA3AA2/F1.J2-L2-O"
	"2-O2-M3JA3CA3EA2/E1.E1.E1.E2/E1.E2/E1.E1.E1.E2/E3EA3BA3JA2-L2-O"
	"2-O2-M2/J3CA2/E2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E2/E3BA2/J2-L2-O"
	"2-O2-M3JA1.C1.E1.E1.E2/E1.E1.E1.E1.E1.E2/E1.E1.E1.E1.B3JA2-L2-O"
	"2-O2-M3JA2/C1.E2/E1.E1.E1.E2/E1.E2/E1.E1.E1.E2/E1.E2/B3JA2-L2-O"
	"2-O2-M3JA1.C1.E1.E1.E2/E1.E1.E1.E1.E1.E2/E1.E1.E1.E1.B3JA2-L2-O"
	"2-O2-M2/J3CA2/E2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E2/E3BA2/J2-L2-O"
	"2-O2-M3JA3CA3EA2/E1.E1.E1.E2/E1.E2/E1.E1.E1.E2/E3EA3BA3JA2-L2-O"
	"2-O2-M1.J2/I3DA3DA1.D2/D1.D1.D1.D1.D1.D2/D1.D3DA3DA2/H1.J2-L2-O"
	"2-O2-M1.K1.J3JA2/J3JA3JA3JA2/J2/J2/J3JA3JA3JA2/J3JA1.J1.J2-L2-O"
	"2-O2-S2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-N2-R2-O"
	"2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O2-O",

	// NZ STAGE 3
	"2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J"
	"2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J"
	"2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J"
	"2/J2/J1.J1.J3JA3JA2/J1.J1.J3JA3JA3JA1.J1.J2/J3JA3JA1.J1.J2/J2/J"
	"2/J2/J1.J2/G2/A3AA2/A1.A2/A2/A1.A2/A2/A1.A2/A3AA2/A2/F1.J2/J2/J"
	"2/J2/J3JA3CA2/E3EA1.E1.E2/E1.E1.E1.E2/E1.E1.E3EA2/E3BA3JA2/J2/J"
	"2/J2/J2/J3CA3EA1.E2/E1.E1.E1.E2/E1.E1.E1.E2/E1.E3EA3BA2/J2/J2/J"
	"2/J2/J1.J3CA2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E3BA1.J2/J2/J"
	"2/J2/J3JA2/C2/E1.E1.E1.E1.E1.E1.E1.E1.E1.E1.E1.E2/E2/B3JA2/J2/J"
	"2/J2/J1.J3CA2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E1.E2/E3BA1.J2/J2/J"
	"2/J2/J2/J3CA3EA1.E2/E1.E1.E1.E2/E1.E1.E1.E2/E1.E3EA3BA2/J2/J2/J"
	"2/J2/J3JA3CA2/E3EA1.E1.E2/E1.E1.E1.E2/E1.E1.E3EA2/E3BA3JA2/J2/J"
	"2/J2/J1.J2/I2/D3DA2/D1.D2/D2/D1.D2/D2/D1.D2/D3DA2/D2/H1.J2/J2/J"
	"2/J2/J1.J1.J3JA3JA2/J1.J1.J3JA3JA3JA1.J1.J2/J3JA3JA1.J1.J2/J2/J"
	"2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J"
	"2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J2/J",

	// ******** Level 1 - CandyLand **********/
	// CANDYLAND STAGE 1 
	"1/K1/K1/K1/S1/S1/K1/S1/S1/K1/S1/S1/S1/K1/S1/S1/K1/S1/S1/K1/K1/K"
	"1/G1/R1/G1/W1/X1/G1/W1/X1/G1/W1/S1/X1/G1/W1/X1/G1/W1/X1/G1/R1/G"
	"1/S1/V1/D1/U1/V1/A1/U1/V1/B1/U1/S1/V1/C1/U1/V1/B1/U1/V1/C1/U1/S"
	"1/W1/X2.R2.N3nA3nF3nK3fA3nK2.N2.N2.N3nK3fA3nK3nF3nA2.N2.S1/W1/X"
	"1/U1/V2.M1/H1/S1/I1/D3mF1/B1/H1/S1/I1/D3mF1/B1/H1/S1/I2.M1/U1/V"
	"1/I1/A3mA1/B2.R2.N2.N2.L2.N2.N2.F2.N2.N2.L2.N2.N2.S1/B3mA1/B1/H"
	"1/W1/X3hF3nA3iF1/W1/I2.M1/H1/X2.M1/W1/I2.M1/H1/X3hF3nA3iF1/W1/X"
	"1/U1/V3mK1/P3mK1/G1/C2.M1/D1/G2.M1/G1/C2.M1/D1/G3mK1/P3mK1/U1/V"
	"1/I1/B3hA3nF3lA2.N2.N2.L2.N2.N2.L2.N2.N2.L2.N2.N3lA3nF3iA1/C1/H"
	"1/W1/X3mK1/P3mK1/F1/B2.M1/A1/F2.M1/F1/B2.M1/A1/F3mK1/P3mK1/W1/X"
	"1/U1/V3hF3nA3iF1/U1/I2.M1/H1/V2.M1/U1/I2.M1/H1/V3hF3nA3iF1/U1/V"
	"1/I1/C3mA1/B2.P2.N2.N2.L2.N2.N2.G2.N2.N2.L2.N2.N2.Q1/B3mA1/D1/H"
	"1/W1/X2.M1/H1/S1/I1/D3mF1/B1/H1/S1/I1/D3mF1/B1/H1/S1/I2.M1/W1/X"
	"1/U1/V2.P2.N3nA3nF3nK3gA3nK2.N2.N2.N3nK3gA3nK3nF3nA2.N2.Q1/U1/V"
	"1/W1/X1/D1/W1/X1/A1/W1/X1/B1/W1/S1/X1/C1/W1/X1/D1/W1/X1/A1/W1/X"
	"1/R1/R1/F1/U1/V1/F1/U1/V1/F1/U1/S1/V1/F1/U1/V1/F1/U1/V1/F1/R1/R",

	// CANDYLAND STAGE 2
	"2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K"
	"1/W1/S1/S1/S1/S1/K1/S1/X1/P1/W1/S1/X1/P1/W1/S1/K1/S1/S1/S1/S1/X"
	"1/R1/W1/S1/S1/S1/V1/A1/U1/S1/V1/A1/U1/S1/V1/A1/U1/S1/S1/S1/X1/R"
	"1/R1/R2.R2.N3nA3nK3fF3nA3nK2.N2.F2.N3nF3nA3fK3nF3nA2.N2.S1/R1/R"
	"1/W1/V2.M1/A1/B1/C3mA1/C1/A1/C2.M1/A1/C1/A3mA1/C1/B1/A2.M1/U1/N"
	"1/R1/A3hA3nK3fF3nA3lK2.N2.F2.N2.L2.N2.F2.N3lF3nA3fK3nF3iA1/A1/R"
	"1/U1/X3mK1/A2.M1/P2.M1/P2.M1/F2.M1/F2.M1/P2.M1/P2.M1/D3mF1/W1/N"
	"1/W1/V3mF1/B2.H2.N2.G2.N2.I1/G2.M1/G2.H2.N2.G2.N2.I1/C3mK1/U1/X"
	"1/R1/A3hP3nK3iF1/H1/S1/I2.H2.N2.L2.N2.I1/H1/S1/I3hF3nK3iA1/A1/R"
	"1/U1/X3mK1/C2.H2.N2.F2.N2.I1/F2.M1/F2.H2.N2.F2.N2.I1/B3mF1/W1/V"
	"1/W1/V3mF1/D2.M1/P2.M1/P2.M1/G2.M1/G2.M1/P2.M1/P2.M1/A3mK1/U1/X"
	"1/R1/A3hA3nF3gK3nA3lF2.N2.G2.N2.L2.N2.G2.N3lK3nA3gF3nK3iA1/A1/R"
	"1/M1/X2.M1/A1/B1/C3mA1/A1/C1/A2.M1/C1/A1/C3mA1/C1/B1/A2.M1/W1/N"
	"1/R1/R2.P2.N3nA3nF3gK3nA3nF2.N2.G2.N3nK3nA3gF3nK3nA2.N2.Q1/R1/R"
	"1/R1/U1/S1/S1/S1/X1/A1/W1/S1/X1/A1/W1/S1/X1/A1/W1/S1/S1/S1/V1/R"
	"1/U1/S1/S1/S1/S1/L1/S1/V1/P1/U1/S1/V1/P1/U1/S1/L1/S1/S1/S1/S1/V",

	// CANDYLAND STAGE 3
	"1/Q1/Q1/S1/S1/S1/S1/S1/Q1/S1/S1/Q1/S1/S1/Q1/S1/S1/S1/S1/S1/Q1/Q"
	"1/Q1/Q1/S1/S1/S1/S1/S1/Q1/S1/S1/Q1/S1/S1/Q1/S1/S1/S1/S1/S1/Q1/Q"
	"1/Q1/Q1/S1/S1/S1/S1/S1/Q1/S1/S1/Q1/S1/S1/Q1/S1/S1/S1/S1/S1/Q1/Q"
	"1/R1/R2.R2.N3fA3nF3sK1/U1/S1/S1/Q1/S1/S1/V3rF3nK3fA2.N2.S1/R1/R"
	"1/R1/R2.M1/P3mF1/P2.H2.N2.N2.S1/G2.R2.N2.N2.I1/P3mK1/P2.M1/R1/R"
	"1/R1/R3hA3nF3lK3nA2.I1/C1/B2.H2.N2.I1/B1/C2.H3nA3lF3nK3iA1/R1/R"
	"1/R1/R3mF1/P3mA1/P2.M1/B1/A2.M1/F2.M1/A1/B2.M1/P3mA1/P3mK1/R1/R"
	"1/Q1/V3hK3nA3gF3nK2.L2.N2.N2.Q1/R2.P2.N2.N2.L3nF3gK3nA3iF1/U1/Q"
	"1/R1/D3mA1/H1/S1/I2.M1/H1/S1/S1/Q1/S1/S1/I2.M1/H1/S1/I3mA1/D1/R"
	"1/Q1/X3hF3nA3fK3nF2.L2.N2.N2.S1/R2.R2.N2.N2.L3nK3fF3nA3iK1/W1/Q"
	"1/R1/R3mK1/P3mA1/P2.M1/B1/A2.M1/G2.M1/A1/B2.M1/P3mA1/P3mF1/R1/R"
	"1/R1/R3hA3nK3lF3nA2.I1/C1/B2.H2.N2.I1/B1/C2.H3nA3lK3nF3iA1/R1/R"
	"1/R1/R2.M1/P3mK1/P2.H2.N2.N2.Q1/F2.P2.N2.N2.I1/P3mF1/P2.M1/R1/R"
	"1/R1/R2.P2.N3gA3nK3qF1/W1/S1/S1/Q1/S1/S1/X3pK3nF3gA2.N2.Q1/R1/R"
	"1/Q1/Q1/S1/S1/S1/S1/S1/Q1/S1/S1/Q1/S1/S1/Q1/S1/S1/S1/S1/S1/Q1/Q"
	"1/Q1/Q1/S1/S1/S1/S1/S1/Q1/S1/S1/Q1/S1/S1/Q1/S1/S1/S1/S1/S1/Q1/Q",

	// ******** Level 2 - Haunted House **********/
	// HAUNTED STAGE 1
	"2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K2-K"
	"2-I2-L2-L2-U2-L2-L2-L2-U2-L2-L2-L2-L2-L2-U2-L2-L2-L2-U2-L2-L2-N"
	"2-G2-H2-K2-V2-K2-K2-K2-V2-K2-K2-K2-K2-K2-V2-K2-K2-K2-V2-K2-M2-Q"
	"2-G2-F1.H1.H3HA1/C3HA3HA3HA1/A1/F1/B3HA3HA3HA1/C3HA1.H1.H2-P2-Q"
	"2-G2-F1.H2/J3HA3HA1.H1/E1.H2/E1.H1/D1.H2/J1.H3HA3HA1/E1.H2-P2-Q"
	"2-G2-F3HA1/A1/B1.H1/A1/B1.H1.H1.H1.H1.H1/A1/B1.H1/A1/B3HA2-P2-Q"
	"2-G2-F3HA3HA1.H3HA3HA1.H1.H1/E1.H2/J1.H1.H3HA3HA1.H3HA3HA2-P2-Q"
	"2-G2-F2/O1.H1/E3HA2/J1.H1/A1/F1/F1/F1/B1.H2/J3HA1/E1.H2/T2-P2-Q"
	"2-G2-F1/C3HA1/A1/F1/B1.H1.H1.H1.H1.H1.H1.H1/A1/F1/B3HA1/C2-P2-Q"
	"2-G2-F2/O1.H2/E3HA1/D1.H1/A1/F1/F1/F1/B1.H1/D3HA2/E1.H2/T2-P2-Q"
	"2-G2-F3HA3HA1.H3HA3HA1.H1.H2/E1.H1/D1.H1.H3HA3HA1.H3HA3HA2-P2-Q"
	"2-G2-F3HA1/A1/B1.H1/A1/B1.H1.H1.H1.H1.H1/A1/B1.H1/A1/B3HA2-P2-Q"
	"2-G2-F1.H1/D3HA3HA1.H2/E1.H1/E1.H2/J1.H1/D1.H3HA3HA2/E1.H2-P2-Q"
	"2-G2-F1.H1.H3HA1/C3HA3HA3HA1/A1/F1/B3HA3HA3HA1/C3HA1.H1.H2-P2-Q"
	"2-G2-C2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-R2-Q"
	"2-D2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B",

	// HAUNTED STAGE 2 
	"2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B"
	"2-I2-L2-L2-U2-L2-L2-L2-U2-L2-L2-L2-L2-L2-U2-L2-L2-L2-U2-L2-L2-N"
	"2-G2-H2-K2-V2-K2-K2-K2-V2-K2-K2-K2-K2-K2-V2-K2-K2-K2-V2-K2-M2-Q"
	"2-G2-F1.H1.H3HA1/C1.H1.H3HA3HA1/E3HA3HA1.H1.H1/C3HA1.H1.H2-P2-Q"
	"2-G2-F1.H2/O3HA2/E3HA2/T2/O3HA1/C3HA2/T2/O3HA1/D3HA2/T1.H2-P2-Q"
	"2-G2-F3HA3HA3HA3HA3HA1.H1/C1.H1.H1.H1/C1.H3HA3HA3HA3HA3HA2-P2-Q"
	"2-G2-F3HA1/A1/F1/F1/B1.H2/T2/O1.H2/T2/O1.H1/A1/F1/F1/B3HA2-P2-Q"
	"2-G2-F3HA3HA3HA3HA1.H1.H1.H1.H1.H1.H1.H1.H1.H3HA3HA3HA3HA2-P2-Q"
	"2-G2-F2/T2/O3HA1/C1.H2/T2/O1.H1/C1.H2/T2/O1.H1/C3HA2/T2/O2-P2-Q"
	"2-G2-F3HA3HA3HA3HA1.H1.H1.H1.H1.H1.H1.H1.H1.H3HA3HA3HA3HA2-P2-Q"
	"2-G2-F3HA1/A1/F1/F1/B1.H2/T2/O1.H2/T2/O1.H1/A1/F1/F1/B3HA2-P2-Q"
	"2-G2-F3HA3HA3HA3HA3HA1.H1/C1.H1.H1.H1/C1.H3HA3HA3HA3HA3HA2-P2-Q"
	"2-G2-F1.H2/O3HA1/E3HA2/T2/O3HA1/C3HA2/T2/O3HA2/J3HA2/T1.H2-P2-Q"
	"2-G2-F1.H1.H3HA1/C1.H1.H3HA3HA1/D3HA3HA1.H1.H1/C3HA1.H1.H2-P2-Q"
	"2-G2-C2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-R2-Q"
	"2-D2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-S",

	// HAUNTED STAGE 3
	"2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B"
	"2-I2-L2-L2-L2-L2-U2-L2-L2-L2-L2-U2-L2-L2-L2-L2-U2-L2-L2-L2-L2-N"
	"2-G2-H2-K2-K2-K2-V2-K2-K2-K2-K2-V2-K2-K2-K2-K2-V2-K2-K2-K2-M2-Q"
	"2-G2-F1.H1.H3HA3HA3HA3HA3HA1.H3HA1.H1/E3HA3HA3HA3HA1.H1.H2-P2-Q"
	"2-G2-F1.H2/O3HA1/A1/F1/F1/B1.H1/E1.H1/C3HA1/E3HA1/A1/B1.H2-P2-Q"
	"2-G2-F3HA3HA3HA3HA1.H1.H1.H1.H1/C1.H1/D1.H1/C3HA3HA3HA3HA2-P2-Q"
	"2-G2-F3HA1/E3HA1/A1/B1.H1/C1.H1.H1.H1.H1.H1/D1/C3HA1/E3HA2-P2-Q"
	"2-G2-F3HA1/C1.H1/D1.H1.H1/E1.H1/D1/C2/O1.H1.H1/D1.H1/C3HA2-P2-Q"
	"2-G2-F3HA3HA3HA1.H3HA1/D1/C1.H1.H1.H1/C1/E3HA1.H3HA3HA3HA2-P2-Q"
	"2-G2-F3HA1/C1.H1/E1.H1.H2/T1/C1/E1.H1/D1.H1.H1/E1.H1/C3HA2-P2-Q"
	"2-G2-F3HA1/D3HA1/C1/E1.H1.H1.H1.H1.H1/C1.H1/A1/B3HA1/D3HA2-P2-Q"
	"2-G2-F3HA3HA3HA3HA1/C1.H1/E1.H1/C1.H1.H1.H1.H3HA3HA3HA3HA2-P2-Q"
	"2-G2-F1.H1/A1/B3HA1/D3HA1/C1.H1/D1.H1/A1/F1/F1/B3HA2/T1.H2-P2-Q"
	"2-G2-F1.H1.H3HA3HA3HA3HA1/D1.H3HA1.H3HA3HA3HA3HA3HA1.H1.H2-P2-Q"
	"2-G2-C2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-A2-R2-Q"
	"2-D2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-B2-S",

	// ******** Level 3 - Toy Factory **********/
	// TOY STAGE 1 
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/L1/L"
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L"
	"1/I1/N2.K2.K3kA3cP3mF3gU3dA3kK3kA3kF3cA3gA3mU3dP3kK2.K2.K1/N1/H"
	"1/I1/N2.K1/R1/M1/W1/D3bU1/C1/W1/M1/W1/D3bF1/C1/W1/M1/S2.K1/N1/H"
	"1/I1/N3kA1/X2.O2.W3wA3wP3wA2.W2.W2.W3wA3wU3wA2.W2.V1/X3kU1/N1/H"
	"1/I1/N3aK1/B2.Y1/R1/S2.K1-K2.K1/A2.K1-K2.K1/R1/S2.T1/B3aA1/N1/H"
	"1/I1/N3hP3dF3yA1/P1/Q2.A2.K2.K1/X2.K2.K2.A1/P1/Q3tF3cU3iK1/N1/H"
	"1/I1/N3nA1-K3yA2.K2.C2.I1/C1/M1/L1/M1/D2.H2.D2.K3tA1-K3nA1/N1/H"
	"1/I1/N3hU3dA3yF1/R1/S2.B2.K2.K1/X2.K2.K2.B1/R1/S3tP3cA3iF1/N1/H"
	"1/I1/N3bF1/A2.Y1/P1/Q2.K1-K2.K1/B2.K1-K2.K1/P1/Q2.T1/A3bP1/N1/H"
	"1/I1/N3kA1/X2.U2.X3xA3xU3xU2.X2.X2.X3xA3xF3xA2.X2.J1/X3kU1/N1/H"
	"1/I1/N2.K1/P1/M1/W1/D3aF1/C1/W1/M1/W1/D3aA1/C1/W1/M1/Q2.K1/N1/H"
	"1/I1/N2.K2.K3kA3cF3mK3fA3dP3kF3kU3kA3cU3fK3mK3dP3kA2.K2.K1/N1/H"
	"1/L1/L1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/F1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L",

	// TOY STAGE 2
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/G1/L1/L1/L1/G1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/G1/G1/G1/G1/L1/Q1-K1/P1/L1/Q1-K1/P1/L1/G1/G1/G1/G1/L1/L"
	"1/N1/N2.R2.D3kP3kU1/B2.O2.W3vK1/B3oA2.W2.V1/B3kU3kA2.C2.S1/N1/N"
	"1/N1/N2.B1/R1/S3kA2.K2.Y1/A3tA3kP3yF1/A2.T2.K3kF1/R1/S2.B1/N1/N"
	"1/N1/N3kA1/P1/Q3kF1-K2.Y1/X2.T1-K2.Y1/X2.T1-K3kA1/P1/Q3kP1/N1/N"
	"1/N1/N3kK3cK3mP3dA2.K2.Y1/B2.T2.K2.Y1/B2.T2.K3cA3mK3dA3kU1/N1/N"
	"1/L1/G1/S3kA1/A2.K1/A2.U2.X2.J1/A2.U2.X2.J1/A2.K1/A3kF1/R1/G1/L"
	"1/N1-K1/N3kF1/X2.K1/H1/D2.K1/C1/L1/D2.K1/C1/I2.K1/X3kA1/N1-K1/N"
	"1/L1/F1/Q3kA1/B2.K1/B2.O2.W2.V1/B2.O2.W2.V1/B2.K1/B3kU1/P1/F1/L"
	"1/N1/N3kA3cK3mA3dU2.K2.Y1/A2.T2.K2.Y1/A2.T2.K3cP3mP3dK3kU1/N1/N"
	"1/N1/N3kF1/R1/S3kP1-K2.Y1/X2.T1-K2.Y1/X2.T1-K3kF1/R1/S3kA1/N1/N"
	"1/N1/N2.A1/P1/Q3kA2.K2.Y1/B3tF3kA3yA1/B2.T2.K3kU1/P1/Q2.A1/N1/N"
	"1/N1/N2.P2.D3kU3kF1/A2.U2.X3jA1/A3uP2.X2.J1/A3kA3kK2.C2.Q1/N1/N"
	"1/L1/L1/F1/F1/F1/F1/L1/S1-K1/R1/L1/S1-K1/R1/L1/F1/F1/F1/F1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L",

	// TOY STAGE 3
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/L1/L1/G1/L1/L1/L1/L1/L1/G1/L1/L1/L1/L1/L1/G1/L1/L1/L1/L"
	"1/L1/L1/G1/Q1-K1/P1/G1/G1/G1/Q1-K1/P1/G1/G1/G1/Q1-K1/P1/G1/L1/L"
	"1/L1/I2.O2.W3wU3wA3vP3kK3cA3mU2.G3mA3dK3kA3oF3wA3wU2.W2.V1/H1/L"
	"1/L1/I2.Y1/A3aA1/A2.T1/R1/W1/D2.B1/C1/M1/S2.Y1/A3aP1/A2.T1/H1/L"
	"1/L1/I3yA1/B3bP1/B2.T1/B2.K2.K2.K2.K2.K1/B2.Y1/B3bA1/B3tA1/H1/L"
	"1/L1/I3uF3xK3xA2.X2.J2.K2.K1/A2.K1/A2.K2.K2.U2.X3xU3xF3jF1/H1/L"
	"1/L1/Q3aA1/C1/M1/W1/D2.K1/C1/Q2.A1/P1/D2.K1/C1/M1/W1/D3aK1/P1/L"
	"1/I1-K3hK3dU3kU3kA3kF2.K2.K2.C2.L2.D2.K2.K3kU3kA3kA3cF3iA1-K1/H"
	"1/L1/S3bA1/C1/W1/M1/D2.K1/C1/S2.B1/R1/D2.K1/C1/W1/M1/D3bP1/R1/L"
	"1/L1/I3oP3wK3wA2.W2.V2.K2.K1/B2.K1/B2.K2.K2.O2.W3wA3wK3vU1/H1/L"
	"1/L1/I3yF1/A3aP1/A2.T1/A2.K2.K2.K2.K2.K1/A2.Y1/A3aP1/A3tA1/H1/L"
	"1/L1/I2.Y1/B3bA1/B2.T1/P1/M1/D2.A1/C1/W1/Q3yF1/B3bU1/B2.T1/H1/L"
	"1/L1/I2.U2.X3xK3xK3jA3kU3cF3mA2.F3mK3dA3kP3uP3xK3xA2.X2.J1/H1/L"
	"1/L1/L1/F1/S1-K1/R1/F1/F1/F1/S1-K1/R1/F1/F1/F1/S1-K1/R1/F1/L1/L"
	"1/L1/L1/A1/A1/F1/A1/A1/A1/A1/A1/F1/A1/A1/A1/A1/A1/F1/A1/A1/L1/L",

	// ******** Level 4 - Disco **********/
	// DISCO STAGE 1
	"1/L1/M1/M1/M1/M1/M1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/I1/N"
	"1/H1/M1/M1/M1/M1/M1/L1/F1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/F1/I1/N"
	"1/N1/R1/M1/M1/M1/M1/I1/P1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/Q1/N1/N"
	"1/N1/N2.B2.C3dA3aA1/B3cA3dA3aA2.B2.C2.D2.A3bA3cA3dA2.A2.B1/N1/N"
	"1/N1/N2.G1/O1/T3fA3gA3hA1/R1/S2.G1/E1/J2.F2/O2/T3iA1/K2.G1/N1/N"
	"1/N1/N3lA1/U1/V3kA1/R1/F1/G1/Q2.L1/U1/V2.K1/U1/V3nA3kA3lA1/N1/N"
	"1/L1/Q3qA3rA3sA3pA1/P1/Q2.S2.P2.Q2.R2.S2.P2.Q2.R3sA1/A3qA1/N1/N"
	"1/L1/F1/M1/M1/D2.A2.B2.C2.D1/K3bA1/K2.D1/W1/X2.C1/C1/Q3bA1/N1/N"
	"1/N1/N3gA3hA3iA2.F2/O2/T2.I3fA3gA3hA2.I1/U1/V2.H3iA3fA3gA1/N1/N"
	"1/N1/N3lA1/R1/D2.K1/U1/V2.N1/K3lA1/K2.N2.K2.L2.M1/C1/M1/M1/G1/I"
	"1/N1/N3qA1/B3sA2.P2.Q2.R2.S2.P2.Q2.R2.S1/R1/S3rA3sA3pA3qA1/R1/I"
	"1/N1/N3bA3cA3dA1/W1/X2.C1/E1/J2.B1/R1/F1/G1/Q3cA2/W2/X3bA1/N1/N"
	"1/N1/N2.G1/K3iA1/U1/V2.H1/U1/V2.G1/P1/Q3fA3gA3hA1/U1/V2.G1/N1/N"
	"1/L1/Q2.L2.M3nA3kA3lA2.M2.N2.K2.L3mA3nA3kA1/A3mA3nA2.K2.L1/N1/N"
	"1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/S1/H1/M1/M1/M1/M1/I1/N"
	"1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L1/M1/M1/M1/M1/I1/N",

	// DISCO STAGE 2
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/F1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L"
	"1/N1/N2.B2.C3dA3aA3bA3cA3dA1/R1/L1/S3dA3aA3bA3cA3dA2.A2.B1/N1/N"
	"1/N1/N2.G2/O2/T3fA1/C1/D3iA1/P1/L1/Q3iA1/C1/D3hA1/O1/T2.G1/N1/N"
	"1/N1/N3lA1/U1/V3kA3lA2.M2.N2.K1/B2.M2.N2.K3lA3mA1/U1/V3lA1/N1/N"
	"1/N1/N3qA3rA3sA1/C1/D2.R1/A2.P2.Q2.R1/A2.P1/C1/D3sA3pA3qA1/N1/N"
	"1/N1/N1/R1/S3dA3aA2.B2.C1/P1/D2.B1/C1/Q2.A2.B3cA3dA1/R1/S1/N1/N"
	"1/N1/H1/L1/L1/D3fA1/K2.H2.I2.F2.G2.H2.I2.F1/K3hA1/C1/L1/L1/I1/N"
	"1/N1/N1/P1/Q3nA3kA2.L2.M1/R1/D2.L1/C1/S2.K2.L3mA3nA1/P1/Q1/N1/N"
	"1/N1/N3qA3rA3sA1/C1/D2.R1/B2.P2.Q2.R1/B2.P1/C1/D3sA3pA3qA1/N1/N"
	"1/N1/N3bA1/W1/X3aA3bA2.C2.D2.A1/A2.C2.D2.A3bA3cA2/W2/X3bA1/N1/N"
	"1/N1/N2.G1/U1/V3fA1/C1/D3iA1/R1/L1/S3iA1/C1/D3hA1/U1/V2.G1/N1/N"
	"1/N1/N2.L2.M3nA3kA3lA3mA3nA1/P1/L1/Q3nA3kA3lA3mA3nA2.K2.L1/N1/N"
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/G1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L1/L",

	// DISCO STAGE 3
	"1/L1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/Q1/P1/M1/M1/M1/G1/M1/M1/M1/Q1/P1/M1/M1/M1/L1/L"
	"1/N1/N2.B2.C3dA3aA3bA1/O1/T3aA3bA3cA2/W2/X3bA3cA2.D2.A2.B1/N1/N"
	"1/N1/N2.G2/O2/T1/K3gA1/U1/V2.F1/A2.H1/U1/V3gA1/K1/W1/X2.G1/N1/N"
	"1/N1/N3lA1/U1/V3kA3lA2.M2.N2.K1/N2.M2.N2.K3lA3mA1/U1/V3lA1/N1/N"
	"1/N1/N3qA3rA3sA3pA1/W1/X2.S1/C1/G1/D2.S1/E1/J3rA3sA3pA3qA1/N1/N"
	"1/L1/L1/M1/M1/S3aA1/U1/V2.D2.A2.B2.C2.D1/U1/V3cA1/R1/M1/M1/L1/L"
	"1/N1/N2-G1/K1/N3fA2.G2.H2.I1/K2.G1/K2.I2.F2.G3hA1/N1/K2-G1/N1/N"
	"1/L1/L1/M1/M1/Q3kA1/E1/J2.N2.K2.L2.M2.N2/O2/T3mA1/P1/M1/M1/L1/L"
	"1/N1/N3qA3rA3sA3pA1/U1/V2.S1/C1/F1/D2.S1/U1/V3rA3sA3pA3qA1/N1/N"
	"1/N1/N3bA2/O2/T3aA3bA2.C2.D2.A1/N2.C2.D2.A3bA3cA1/O1/T3bA1/N1/N"
	"1/N1/N2.G1/U1/V1/K3gA2/W2/X2.F1/B2.H1/O1/T3gA1/K1/U1/V2.G1/N1/N"
	"1/N1/N2.L2.M3nA3kA3lA1/U1/V3kA3lA3mA1/U1/V3lA3mA3nA2.K2.L1/N1/N"
	"1/L1/L1/M1/M1/M1/S1/R1/M1/M1/M1/F1/M1/M1/M1/S1/R1/M1/M1/M1/L1/L"
	"1/L1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/M1/M1/M1/L1/L1/M1/M1/M1/L1/L",

	// ******** Level 5 - Waterworks **********/
	// WATERWORKS STAGE 1
	"1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P"
	"1/P1/P1/L1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/L1/P1/P"
	"1/P1/O1/A1/G1/H1/F1/G1/H1/N1/L1/L1/L1/L1/L1/L1/P1/L1/H1/A1/N1/P"
	"1/P1/O2.I2.K3jA1/N1/K1/K1/H3iA3kA3kA2.K2.K2.J1/F3iA2.K2.J1/N1/P"
	"1/P1/O2.F1/C3fA1/B3iA2.K2.K2.O1/I1/K1/K1/E3fA1/B3fA1/C2.F1/N1/P"
	"1/P1/O3fA1/F3gA3mA3hA1/C1/A2.F1/B2.I2.K2.K3pA3kA3hA1/F3fA1/N1/P"
	"1/P1/O3fA1/G1/E3fA1/D1/H2.I2.L2.K2.O1/D1/J3fA1/D1/K1/H3fA1/N1/P"
	"1/P1/O3gA3kA3kA3lA2.M2.K2.O1/I1/J2.G2.J1/F2.N3kA3kA3kA3hA1/G1/P"
	"1/P1/L1/K1/K1/K1/E2.F1/C2.F1/G1/P1/J2.F1/B2.F1/D1/K1/K1/K1/M1/P"
	"1/P1/J3iA3kA3kA3kA2.O1/F2.G2.J1/G1/H2.N2.K2.L3mA3kA3kA3jA1/N1/P"
	"1/P1/O3fA1/I1/K1/E3fA1/G1/E2.N2.K2.M2.H1/I1/E3fA1/D1/J3fA1/N1/P"
	"1/P1/O3fA1/F3iA3kA3pA2.K2.K2.H1/C2.F1/A1/B3iA3lA3jA1/F3fA1/N1/P"
	"1/P1/O2.F1/B3fA1/C3fA1/D1/K1/K1/H2.N2.K2.K3hA1/C3fA1/B2.F1/N1/P"
	"1/P1/O2.G2.K3hA1/F2.G2.K2.K3kA3kA3hA1/I1/K1/K1/O3gA2.K2.H1/N1/P"
	"1/P1/O1/A1/I1/M1/P1/M1/M1/M1/M1/M1/M1/O1/I1/J1/F1/I1/J1/A1/N1/P"
	"1/P1/P1/M1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P",

	// WATERWORKS STAGE 2
	"1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P"
	"1/P1/P1/L1/P1/P1/P1/P1/P1/P1/P1/L1/P1/P1/P1/P1/P1/P1/P1/L1/P1/P"
	"1/P1/P1/L1/L1/L1/L1/L1/L1/L1/O1/A1/N1/L1/L1/L1/L1/L1/L1/L1/P1/P"
	"1/P1/O2.I2.K3kA3mA3kA3kA3jA1/F2-Q1/F3iA3kA3kA3mA3kA2.K2.J1/N1/P"
	"1/P1/O2.F1/I1/J3fA1/I1/J2.F1/G1/K1/H2.F1/I1/J3fA1/I1/J2.F1/N1/P"
	"1/P1/O3fA1/G1/H3fA1/G1/H2.N2.K2.M2.K2.O1/G1/H3fA1/G1/H3fA1/N1/P"
	"1/P1/O3gA3kA3mA3lA2.K2.M2.H1/C2.F1/C2.G2.M2.K3lA3mA3kA3hA1/N1/P"
	"1/P1/L1/K1/J3fA1/A1/C2.F1/D1/H2.F1/G1/E2.F1/C1/A3fA1/I1/K1/L1/P"
	"1/O1/A2-Q1/F3fA1/D1/O2.N2.K2.K2.P2.K2.K2.O1/N1/E3fA1/F2-Q1/A1/N"
	"1/P1/M1/K1/H3fA1/A1/B2.F1/D1/J2.F1/I1/E2.F1/B1/A3fA1/G1/K1/M1/P"
	"1/P1/O3iA3kA3lA3mA2.K2.L2.J1/B2.F1/B2.I2.L2.K3mA3lA3kA3jA1/N1/P"
	"1/P1/O3fA1/I1/J3fA1/I1/J2.N2.K2.L2.K2.O1/I1/J3fA1/I1/J3fA1/N1/P"
	"1/P1/O2.F1/G1/H3fA1/G1/H2.F1/I1/K1/J2.F1/G1/H3fA1/G1/H2.F1/N1/P"
	"1/P1/O2.G2.K3kA3lA3kA3kA3hA1/F2-Q1/F3gA3kA3kA3lA3kA2.K2.H1/N1/P"
	"1/P1/P1/M1/M1/M1/M1/M1/M1/M1/O1/A1/N1/M1/M1/M1/M1/M1/M1/M1/P1/P"
	"1/P1/P1/M1/P1/P1/P1/P1/P1/P1/P1/M1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P",

	// WATERWORKS STAGE 3 
	"1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P"
	"1/P1/P1/L1/P1/P1/P1/P1/P1/P1/P1/L1/P1/P1/P1/P1/P1/P1/P1/L1/P1/P"
	"1/P1/P1/L1/L1/L1/P1/L1/L1/L1/O1/A1/N1/L1/L1/L1/L1/L1/L1/L1/P1/P"
	"1/P1/O2.I2.K3jA1/F2.I2.K2.J1/G1/K1/H2.I2.K2.J1/F3iA2.K2.J1/N1/P"
	"1/P1/O2.F1/A3fA1/B3fA1/C2.G2.M2.K2.M2.H1/C3fA1/B3fA1/A2.F1/N1/P"
	"1/P1/O3nA3kA3pA3kA3oA1/G1/E2.F1/C2.F1/D1/H3nA3kA3pA3kA3oA1/N1/P"
	"1/P1/O3fA1/A3fA1/C3gA2.K2.M2.H1/F2.G2.M2.K3hA1/C3fA1/A3fA1/N1/P"
	"1/P1/O3gA3kA3oA1/G1/K1/E2.F1/D1/L1/E2.F1/D1/K1/H3nA3kA3hA1/N1/P"
	"1/P1/P1/K1/E3nA2.K2.K2.K2.P2.K2.K2.K2.P2.K2.K2.K3oA1/D1/K1/P1/P"
	"1/P1/O3iA3kA3oA1/I1/K1/E2.F1/D1/M1/E2.F1/D1/K1/J3nA3kA3jA1/N1/P"
	"1/P1/O3fA1/A3fA1/B3iA2.K2.L2.J1/F2.I2.L2.K3jA1/B3fA1/A3fA1/N1/P"
	"1/P1/O3nA3kA3pA3kA3oA1/I1/E2.F1/B2.F1/D1/J3nA3kA3pA3kA3oA1/N1/P"
	"1/P1/O2.F1/A3fA1/C3fA1/B2.I2.L2.K2.L2.J1/B3oA1/C3fA1/A2.F1/N1/P"
	"1/P1/O2.G2.K3hA1/F2.G2.K2.H1/I1/K1/J2.G2.K2.H1/F3gA2.K2.H1/N1/P"
	"1/P1/P1/M1/M1/M1/P1/M1/M1/M1/O1/A1/N1/M1/M1/M1/P1/M1/M1/M1/P1/P"
	"1/P1/P1/M1/P1/P1/P1/P1/P1/P1/P1/M1/P1/P1/P1/P1/P1/P1/P1/P1/P1/P",

	// ******** Level 6 - Underworld **********/
	// Underworld STAGE 1
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/G1/G1/G1/G1/L1/G1/G1/G1/G1/G1/G1/G1/L1/G1/G1/G1/G1/L1/L"
	"1/L1/I2.Y2.Y3yA3yA1/N2.Y3yA3yA2.Y3yA3yA2.Y1/N3yA3yA2.Y2.Y1/H1/L"
	"1/L1/I2.Y1/R1/D3yA1/B2.Y2/T3yA1/A3yA2/J2.Y1/B3yA1/C1/S2.Y1/H1/L"
	"1/L1/I3yA1/B3yA3yA3yA2.Y2.Y2.Y1/N2.Y2.Y2.Y3yA3yA3yA1/B3yA1/H1/L"
	"1/L1/I3yA3yA3yA2-R2-D2.Y2-K2.Y1/B2.Y2-K2.Y2-C2-S3yA3yA3yA1/H1/L"
	"1/L1/I3yA2/O3yA2-N2.Y2.Y2.Y2.Y2.Y2.Y2.Y2.Y2.Y2-N3yA2/E3yA1/H1/L"
	"1/L1/I3yA3yA3yA2-N2.Y1/C1/M1/D2.Y1/C1/M1/D2.Y2-N3yA3yA3yA1/H1/L"
	"1/L1/I3yA2/J3yA2-N2.Y2.Y2.Y2.Y2.Y2.Y2.Y2.Y2.Y2-N3yA2/T3yA1/H1/L"
	"1/L1/I3yA3yA3yA2-P2-D2.Y2-K2.Y1/A2.Y2-K2.Y2-C2-Q3yA3yA3yA1/H1/L"
	"1/L1/I3yA1/A3yA3yA3yA2.Y2.Y2.Y1/N2.Y2.Y2.Y3yA3yA3yA1/A3yA1/H1/L"
	"1/L1/I2.Y1/P1/D3yA1/A2.Y2/E3yA1/B3yA2/O2.Y1/A3yA1/C1/Q2.Y1/H1/L"
	"1/L1/I2.Y2.Y3yA3yA1/N2.Y3yA3yA2.Y3yA3yA2.Y1/N3yA3yA2.Y2.Y1/H1/L"
	"1/L1/L1/F1/F1/F1/F1/L1/F1/F1/F1/F1/F1/F1/F1/L1/F1/F1/F1/F1/L1/L"
	"1/L1/L1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G1/G",

	// Underworld STAGE 2
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L"
	"1/L1/L1/G1/G1/G1/L1/G1/G1/G1/L1/G1/L1/G1/G1/G1/L1/G1/G1/G1/L1/L"
	"1/L1/I2.Y2.Y3yA1/B2.Y2.Y2.Y1/P1/M1/Q2.Y2.Y2.Y1/B3yA2.Y2.Y1/H1/L"
	"1/L1/I2.Y2-K3yA3yA3yA2-A2.Y3yA3yA3yA2.Y2-A3yA3yA3yA2/O2.Y1/H1/L"
	"1/L1/I3yA3yA3yA1/K3yA2-H2-M2-D2.Y2-C2-M2-I3yA1/K3yA3yA3yA1/H1/L"
	"1/L1/I3yA1/K3yA2.Y2.Y2-B2.Y2.Y2.Y2.Y2.Y2-B2.Y2.Y3yA1/K3yA1/H1/L"
	"1/L1/I3yA3yA3yA2-A2.Y2.Y2.Y2/E2.Y2-A2.Y2.Y2.Y2-A3yA3yA3yA1/H1/L"
	"1/L1/L1/D3yA2-C2-L2-D2.Y2/O2-A2.Y2-B2/T2.Y2-C2-L2-D3yA1/C1/L1/L"
	"1/L1/I3yA3yA3yA2-B2.Y2.Y2.Y2-B2.Y2/J2.Y2.Y2.Y2-B3yA3yA3yA1/H1/L"
	"1/L1/I3yA1/K3yA2.Y2.Y2-A2.Y2.Y2.Y2.Y2.Y2-A2.Y2.Y3yA1/K3yA1/H1/L"
	"1/L1/I3yA3yA3yA1/K3yA2-H2-M2-D2.Y2-C2-M2-I3yA1/K3yA3yA3yA1/H1/L"
	"1/L1/I2.Y2/E3yA3yA3yA2-B2.Y3yA3yA3yA2.Y2-B3yA3yA3yA2-K2.Y1/H1/L"
	"1/L1/I2.Y2.Y3yA1/A2.Y2.Y2.Y1/R1/M1/S2.Y2.Y2.Y1/A3yA2.Y2.Y1/H1/L"
	"1/L1/L1/F1/F1/F1/L1/F1/F1/F1/L1/F1/L1/F1/F1/F1/L1/F1/F1/F1/L1/L"
	"1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L1/L",

	// Underworld STAGE 3
	"1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L"
	"1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L"
	"1/N2-R2-M2-M2-M2-M2-M2-M2-M2-M2-F2-M2-M2-M2-M2-M2-M2-M2-M2-S1/N"
	"1/N2-N2.Y2.Y3yA3yA3yA3yA3yA2.Y2-N2.Y3yA3yA3yA3yA3yA2.Y2.Y2-N1/N"
	"1/N2-N2.Y2-K1/K3yA1/R1/M1/D2.Y2-B2.Y1/C1/M1/S3yA1/K2/J2.Y2-N1/N"
	"1/N2-N3yA3yA3yA3yA1/N2.Y2.Y2.Y2.Y2.Y2.Y2.Y1/N3yA3yA3yA3yA2-N1/N"
	"1/N2-N3yA1/C1/D3yA1/B2.Y1/R1/D2.Y1/C1/S2.Y1/B3yA1/C1/D3yA2-N1/N"
	"1/N2-N3yA3yA2.Y2.Y2.Y2.Y1/B2/E2.Y2/T1/B2.Y2.Y2.Y2.Y3yA3yA2-N1/N"
	"1/N2-H2-D3yA1/K2/O1/K2.Y2.Y2.Y2.Y2.Y2.Y2.Y1/K2/J1/K3yA2-C2-I1/N"
	"1/N2-N3yA3yA2.Y2.Y2.Y2.Y1/A2/J2.Y2/O1/A2.Y2.Y2.Y2.Y3yA3yA2-N1/N"
	"1/N2-N3yA1/C1/D3yA1/A2.Y1/P1/D2.Y1/C1/Q2.Y1/A3yA1/C1/D3yA2-N1/N"
	"1/N2-N3yA3yA3yA3yA1/N2.Y2.Y2.Y2.Y2.Y2.Y2.Y1/N3yA3yA3yA3yA2-N1/N"
	"1/N2-N2.Y2/T1/K3yA1/P1/M1/D2.Y2-A2.Y1/C1/M1/Q3yA1/K2-K2.Y2-N1/N"
	"1/N2-N2.Y2.Y3yA3yA3yA3yA3yA2.Y2-N2.Y3yA3yA3yA3yA3yA2.Y2.Y2-N1/N"
	"1/N2-P2-M2-M2-M2-M2-M2-M2-M2-M2-G2-M2-M2-M2-M2-M2-M2-M2-M2-Q1/N"
	"1/L1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/M1/L",
};

struct _leveldata LevelData[LEVELYSIZE][LEVELXSIZE];
extern char bSpecialDim;
extern SpecialStruct specialDat[4][8];

// Draw the level (too many globals)
// Always closes the list
// returns 1 if paused, else 0.
int DrawLevel() {
	SPRITE spr;
	int x, y, idx;
	int nDestructiblesLeft = 0;

	// set up collision buffer
	clearbuffer();

	// Increment the frame counter
	nGameFrames++;

	// Update the BG Animation counters
	nBgCountA--;
	if (!nBgCountA) {
		nBgCountA=nBgSpeedA;
		nBgAnimA++;
		nBgAnimA&=0x03;
	}
	nBgCountB--;
	if (!nBgCountB) {
		nBgCountB=nBgSpeedB;
		nBgAnimB++;
		nBgAnimB&=0x03;
	}
	nBgCountC--;
	if (!nBgCountC) {
		nBgCountC=nBgSpeedC;
		nBgAnimC++;
		nBgAnimC&=0x03;
	}

	// We're all ready, wait for the PVR to be
	pvr_scene_begin();

	// Just the sFX one (note: diagonal quad to replace the old triangle)
	if (sFx < FX16_ONE*4) {
		// no texture, solid black quad (nearly a triangle, but kept quad for the engine's sake)
	    G3_PolygonAttr(GX_LIGHTMASK_NONE,  		// no lights
	                   GX_POLYGONMODE_MODULATE,	// Modulation mode
	                   GX_CULL_NONE,       		// cull none
	                   POLY_MISC,          		// polygon ID(0 - 63)
	                   31,                 		// alpha(0 - 31 0-wireframe,31=opaque)
	                   0                   		// OR of GXPolygonAttrMisc's value
	        );
	    myG3_Color(0,0,0);

		// work out the quad - kind of a distorted parallelogram
		G3_Begin(GX_BEGIN_QUADS);
		{
			G3_Vtx(-FX16_ONE+sFx, FX16_ONE, 0);
			G3_Vtx(-FX16_ONE*3+sFx, -FX16_ONE, 0);
			G3_Vtx(FX16_ONE+sFx, -FX16_ONE, 0);
			G3_Vtx(FX16_ONE+sFx, FX16_ONE, 0);
		}
		G3_End();

		// reset the color (bSpecialDim can't be set at this point, so it's okay)
	    myG3_Color(31,31,31);
		
		sFx+=((fx16) 0x00000400L);	// about 1/4
	}

	// Draw walls
	spr.xd=0;
	spr.yd=0;
	spr.alpha=31;
	spr.nDepth=DEPTH_512x512x8;
	spr.txr_addr=txr_level;
	spr.pal_addr=pal_level;
	
	
	// make sure the buffer clear is finished before we proceed
	MI_WaitDma(GENERIC_DMA_CHANNEL);
	
	for (y=0; y<LEVELYSIZE; y++) {
		for (x=LEVELXSIZE-1; x>=0; x--) {
			int TileOffset;
			
			// get coordinates
			spr.x=x*GRIDSIZE+PLAYFIELDXOFF;
			spr.y=y*GRIDSIZE+PLAYFIELDYOFF;

			// fill in collision buffer
			if (LevelData[y][x].isPassable == false) {
				if (LevelData[y][x].nDestructible > 0) {
					drawbuffer(spr.x, spr.y, TYPE_BOX);
					// destructible
					spr.z=(fx16)2048;
				} else {
					// 3d wall
					drawbuffer(spr.x, spr.y, TYPE_WALL);
					spr.z=(fx16)2044;
				}
			} else {
				// flat ground
				spr.z=(fx16)2050;
			}
			
			// check for exploding crate
			if (LevelData[y][x].nDestructible > 1) {
				if ((nFrames&3) == 0) {
					LevelData[y][x].nDestructible++;
					if (LevelData[y][x].nDestructible==5) {		// done
						LevelData[y][x].nDestructible=0;
						// if it's a push tile, don't leave any remainder underneath
						if (LevelData[y][x].nPush) {
							LevelData[y][x].nTile=(LevelData[y][x].nBaseTile&0x7f)-1;
							LevelData[y][x].nPage=(LevelData[y][x].nBaseTile&0x80)?1:2;
							LevelData[y][x].nBaseTile=0;
						} else {
							LevelData[y][x].nTile+=4;				// final tile is 4 out from first
						}
						LevelData[y][x].isPassable=true;
						LevelData[y][x].is3D=false;

						// 1 is lightning, 2 is speed
						if (gOptions.Powers & POW_POWERUPS) {
							if (LevelData[y][x].nPowerup==0) {
								if (gStageSpecialEffect&STAGE_EFFECT_PWRUP_ALWAYS_BOOT) {
									LevelData[y][x].nPowerup=2;
								} else if (gStageSpecialEffect&STAGE_EFFECT_PWRUP_ALWAYS_BOLT) {
									LevelData[y][x].nPowerup=1;
								} else if ((ch_rand()&0xf) >= 10) {
									// Powerup! (1 or 2)
									LevelData[y][x].nPowerup=(int)(ch_rand()&0x01)+1;
								} else if ((gStageSpecialEffect&STAGE_EFFECT_BOXED_SHEEP)&&(nTotalSheep > 0)) {
									if (((ch_rand()&0xf) >= 7) || (g_DestructiblesLeft<4)) {
										RestartSheep(spr.x, spr.y, 0, 0);
										nTotalSheep--;
									}
								}
							}
						}
					}
				}
			} else if (LevelData[y][x].nDestructible == 1) {
				nDestructiblesLeft++;
			}

			// no more work if offscreen
			if ((spr.x < nOffsetX-TILESIZE) || (spr.x > nOffsetX+304)) {
				continue;
			}
			if ((spr.y < nOffsetY-TILESIZE) || (spr.y > nOffsetY+240)) {
				continue;
			}

			switch (LevelData[y][x].nPage) {
				default:	// fall through
				case 1:		TileOffset=(0*100)+(nBgAnimA*25); break;
				case 2:		TileOffset=(1*100)+(nBgAnimB*25); break;
				case 3:		TileOffset=(2*100)+(nBgAnimC*25); break;
			}

			spr.is3D=LevelData[y][x].is3D;
			spr.tilenumber=LevelData[y][x].nTile + TileOffset;

			// update destructible animation
			if (LevelData[y][x].nDestructible > 1) {
				// Box animation!
				spr.tilenumber+=LevelData[y][x].nDestructible-1;
			}
			
			// check for lighting specials (such as Angel)
			if (bSpecialDim) {
				int nRange = 0;
				if (specialDat[bSpecialDim-1][0].type == SP_ANGELLIGHT) {
					nRange = (spr.x - herder[bSpecialDim-1].spr.x)*(spr.x - herder[bSpecialDim-1].spr.x) +
							 (spr.y - herder[bSpecialDim-1].spr.y)*(spr.y - herder[bSpecialDim-1].spr.y);
				}
				if (specialDat[bSpecialDim-1][0].type == SP_DISCOBALL) {
					nRange = (spr.x - specialDat[bSpecialDim-1][0].spr.x)*(spr.x - specialDat[bSpecialDim-1][0].spr.x) +
							 (spr.y - (specialDat[bSpecialDim-1][0].spr.y+GRIDSIZE))*(spr.y - (specialDat[bSpecialDim-1][0].spr.y+GRIDSIZE));
				}
				if (specialDat[bSpecialDim-1][0].type == SP_GIANTDISCO) {
					nRange = (spr.x - herder[bSpecialDim-1].spr.x)*(spr.x - herder[bSpecialDim-1].spr.x) +
							 (spr.y - herder[bSpecialDim-1].spr.y)*(spr.y - herder[bSpecialDim-1].spr.y);
				}
				if (nRange > 0) {
					if (nRange < specialDat[bSpecialDim-1][0].misccnt*specialDat[bSpecialDim-1][0].misccnt) {
						myG3_Color(31,31,31);
						// destroy any destructible objects we hit
						if (LevelData[y][x].nDestructible == 1) {
							LevelData[y][x].nDestructible=2;
							herder[bSpecialDim-1].score+=10;
						}
					} else {
						myG3_Color(15,15,15);
					}
				}
			}
			
			// check for destructibles that need ground underneath
			if (LevelData[y][x].nBaseTile != 0) {
				SPRITE tmp;

				tmp.x=spr.x;
				tmp.y=spr.y;
				tmp.z=spr.z+(fx16)0x2;
				tmp.alpha=31;
				tmp.nDepth=DEPTH_512x512x8;
				tmp.txr_addr=txr_level;
				tmp.pal_addr=pal_level;
				tmp.tilenumber=(LevelData[y][x].nBaseTile&0x7f)-1+((LevelData[y][x].nBaseTile&0x80)?(0*100+nBgAnimA*25):(1*100+nBgAnimB*25));
				tmp.is3D=false;
				SortSprite(&tmp, LevelMap, POLY_BG);
			}
			
			if (LevelData[y][x].nPowerup==1) {		// Lightning powerup
				SPRITE tmp;

				tmp.x=spr.x;
				tmp.y=spr.y;
				tmp.z=spr.z-(fx16)0x8;
				tmp.alpha=31;
				tmp.nDepth=DEPTH_256x256x4;
				tmp.txr_addr=txr_sprites; 
				tmp.pal_addr=pal_sprites;
				tmp.tilenumber=(int)((nGameFrames>>3)%4+5); 
				tmp.is3D=true;
				SortSprite(&tmp, txrmap_sprites, POLY_MISC);
			}
			if (LevelData[y][x].nPowerup==2) {		// Speed powerup
				SPRITE tmp;

				tmp.x=spr.x;
				tmp.y=spr.y;
				tmp.z=spr.z-(fx16)0x8;
				tmp.alpha=31;
				tmp.nDepth=DEPTH_256x256x4;
				tmp.txr_addr=txr_sprites; 
				tmp.pal_addr=pal_sprites;
				tmp.tilenumber=(int)((nGameFrames>>3)%4);
				tmp.is3D=true;
				SortSprite(&tmp, txrmap_sprites, POLY_MISC);
			}
			SortSprite(&spr, LevelMap, POLY_BG);
		}
	}
	
	// update the global flag
	g_DestructiblesLeft = nDestructiblesLeft;
 
	// If ghost sheep are on, merge in the ghost walls (NZ level - simplified)
	if (gStageSpecialEffect&STAGE_EFFECT_GHOST_SHEEP) {
		char *pDat=&Level[0][0];

		for (y=0; y<LEVELYSIZE; y++) {
			for (x=0; x<LEVELXSIZE; x++, pDat+=3) {
				if ((*pDat == '3') || (*(pDat+1)=='.')) {
					continue;
				}
				spr.x=x*GRIDSIZE+PLAYFIELDXOFF;
				spr.y=y*GRIDSIZE+PLAYFIELDYOFF;
				mergebuffer(spr.x, spr.y, TYPE_GHOSTWALL);
			}
		}
	}

	if (nGameCountdown>0) {
		nGameCountdown--;
		if (nGameCountdown>50) {
			// Ready! or Paused
			for (idx=0; idx<4; idx++) {
				if ((herder[idx].type&PLAY_MASK) != PLAY_NONE) {
					SortSprite(&herder[idx].spr, herder[idx].map, POLY_HERD);
				}
			}
			
			if (fPaused > 0) {
				// ** PAUSE MENU **
				u16 btns = 0;
				int nSelection;
			
				// This holds us in the paused state (which is >50) 
				nGameCountdown=52;
				btns = GetController(gHumanPlayer);
				 
				if (MenuScr_DrawFrame(&nSelection)) 
				{
					// We have to get off our lazy butts and do something
					switch (nSelection)
					{
						case MENU_CONTINUE:
							btns = CONT_START;		// fake start being pressed again
							break;
						
						case MENU_SAVE:
							// We need to save the game here
							doVMUSave(0, 0);
							// restart the music
							StartLevelMusic(level);
							break;
						
						case MENU_QUIT: 
							{
								
								MenuScr_CloseMenu(0);	// animate the close
								int nConfirm = doMenu(MENU_QUIT, NULL);
								if (MENU_QUIT_YES == nConfirm) {
									MenuScr_CloseMenu(0);
									return -99;
								} else {
									MenuScr_InitMenu(MENU_PAUSE);
								}
							}
							break;
						
						default:	// covers both OK and BACK
							btns = CONT_START;		// fake start being pressed again
					}
				}
			
				if ((btns & CONT_START) && (!(btns & CONT_A))) {
					if (fPaused==1) {
						MenuScr_CloseMenu(0);
						MapScr_Init(level, 1);
						fPaused=-1;
						nGameCountdown=1;
					}
				} else {
					if (!(btns & CONT_START)) {
						// start was released
						fPaused=1;
					}
				} 
			} else {
				// ready
				DrawReady();
			}

			pvr_scene_finish();

			return 1;
		}
		if (nGameCountdown == 0) {
			Clear2D();
		} else {
			// Go! (holds from 50 down to 0) (overwrites the Ready! so no clear needed)
			DrawGo();
		}
	}

	return 0;
}

// Prepares the level, and loads the gfx
void LoadLevel(int nWorld, int nStage) {
	char *tmp;
	int x,y;
	int nNumDest=0;
	
	/* there's always SOME */
	g_DestructiblesLeft = 0;		// this is only needed really for the toy factory boxed sheep
	
	/* Load level into LevelData */
	tmp=&Level[nWorld*3+nStage][0];
	for (y=0; y<LEVELYSIZE; y++) {
		for (x=0; x<LEVELXSIZE; x++) {
			// defaults
			LevelData[y][x].nPowerup=0;
			LevelData[y][x].nDestructible=0;
			LevelData[y][x].nBaseTile=0;
			LevelData[y][x].nPush=0;
			// Texture page
			// page 3 is special
			if ((*tmp) == '3') {
				nNumDest++;
				LevelData[y][x].nPage=3; 
				LevelData[y][x].nDestructible=1;
				LevelData[y][x].is3D=true;
				LevelData[y][x].isPassable=false;
				g_DestructiblesLeft++;
				tmp++;
				LevelData[y][x].nBaseTile=*(tmp++)+1;
				if (LevelData[y][x].nBaseTile > 'Z') {
					LevelData[y][x].nBaseTile-='a';
				} else {
					LevelData[y][x].nBaseTile-='A';
					LevelData[y][x].nBaseTile|=0x80;	// page 1 flag
				}
			} else {
				switch (*(tmp++)) {
					default:
					case '1': LevelData[y][x].nPage=1; break;
					case '2': LevelData[y][x].nPage=2; break;
				}
				// Tile type
				switch (*(tmp++)) {
					default:
					case '-': LevelData[y][x].is3D=false; LevelData[y][x].isPassable=false; break;
					case '.': LevelData[y][x].is3D=false; LevelData[y][x].isPassable=true;  break;
					case '/': LevelData[y][x].is3D=true;  LevelData[y][x].isPassable=false; break;
				}
			}
			// Main Tile number
			LevelData[y][x].nTile=(*(tmp++))-'A';
			if (nWorld == LEVEL_TOY) {
				// Special hacky code to handle the toy factory conveyor belts
				// base tiles are all +1 because 0 means no base tile
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==9)) || (LevelData[y][x].nBaseTile==9+1)) {
					LevelData[y][x].nPush=4;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==14)) || (LevelData[y][x].nBaseTile==14+1)) {
					LevelData[y][x].nPush=2;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==19)) || (LevelData[y][x].nBaseTile==19+1)) {
					LevelData[y][x].nPush=3;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==20)) || (LevelData[y][x].nBaseTile==20+1)) {
					LevelData[y][x].nPush=1;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==21)) || (LevelData[y][x].nBaseTile==21+1)) {
					LevelData[y][x].nPush=3;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==22)) || (LevelData[y][x].nBaseTile==22+1)) {
					LevelData[y][x].nPush=2;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==23)) || (LevelData[y][x].nBaseTile==23+1)) {
					LevelData[y][x].nPush=4;
				}
				if (((LevelData[y][x].nPage==2)&&(LevelData[y][x].nTile==24)) || (LevelData[y][x].nBaseTile==24+1)) {
					LevelData[y][x].nPush=1;
				}
				// end special hacky section
			}
		}
	}

	// default of no sheep
	gStageSpecialEffect&=~STAGE_EFFECT_GHOST_SHEEP;
	// otherwise only the haunted and underworld levels below will set the value to 1

	/* Load level GFX */
	switch (nWorld) {
	case LEVEL_NZ:
		load_bmp_block_mask("gfx/Stages/nz.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/nz_map.txt", LevelMap);
		break;

	case LEVEL_CANDY:
		load_bmp_block_mask("gfx/Stages/candy.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/candy_map.txt", LevelMap);
		gStageSpecialEffect |= STAGE_EFFECT_SUGAR_RUSH;
		MapScr_SetSpecialText("Sheep sugar rush");
		break;

	case LEVEL_HAUNTED:
		load_bmp_block_mask("gfx/Stages/haunted.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/haunted_map.txt", LevelMap);
		gStageSpecialEffect|=STAGE_EFFECT_GHOST_SHEEP;
		MapScr_SetSpecialText("Stun ghost sheep");
		break;

	case LEVEL_TOY:
		load_bmp_block_mask("gfx/Stages/toy.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/toy_map.txt", LevelMap);
		gStageSpecialEffect |= STAGE_EFFECT_BOXED_SHEEP;
		MapScr_SetSpecialText(" Sheep in boxes ");
		break;

	case LEVEL_DISCO:
		load_bmp_block_mask("gfx/Stages/disco.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/disco_map.txt", LevelMap);
		break;

	case LEVEL_WATER:
		load_bmp_block_mask("gfx/Stages/water.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/water_map.txt", LevelMap);
		break;

	case LEVEL_UNDERWORLD:
		load_bmp_block_mask("gfx/Stages/underworld.bmp", NULL, txr_level, pal_level, -1);
		load_level_map("gfx/Stages/underworld_map.txt", LevelMap);
		gStageSpecialEffect|=STAGE_EFFECT_GHOST_SHEEP;
		if (isMultiplayer) {
			MapScr_SetSpecialText("Stun ghost sheep");
		}
		break;

	default:
		debug("WTF? Requested world %d\n", nWorld);
		break;
	}
}

// starts the level music
void StartLevelMusic(int nWorld) {
	switch (nWorld) {
	case LEVEL_NZ:
		sound_start(SONG_NEWZEALAND, 1);
		break;

	case LEVEL_CANDY:
		sound_start(SONG_CANDYLAND, 1);
		break;

	case LEVEL_HAUNTED:
		sound_start(SONG_HAUNTED, 1);
		break;

	case LEVEL_TOY:
		sound_start(SONG_FACTORY, 1);
		break;

	case LEVEL_DISCO:
		sound_start(SONG_DISCO, 1);
		break;

	case LEVEL_WATER:
		sound_start(SONG_WATERWORKS, 1);
		break;

	case LEVEL_UNDERWORLD:
		sound_start(SONG_HELL, 1);
		break;

	default:
		debug("WTF? Requested world %d\n", nWorld);
		break;
	}
}
